FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/autogluon-training:1.1.1-cpu-py311-ubuntu20.04

# Copy the contents of the tab-benchmark folder to the container - run from tabflow
COPY ../ .
COPY ./tabflow/evaluate.py .

# Install the required packages
RUN pip install -e tabrepo \
    && pip install -e autogluon-bench \
    && pip install -e autogluon-benchmark

# Install pytabkit and seaborn
RUN pip install pytabkit seaborn

# Generate configs and give permissions
RUN chmod +x ./tabrepo/scripts/run_generate_all_configs.py
RUN python ./tabrepo/scripts/run_generate_all_configs.py
RUN chmod +x ./evaluate.py